language: php
dist: trusty

php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - composer self-update

before_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then NTESTER_FLAGS="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; else NTESTER_FLAGS=""; fi
    - phpenv config-rm xdebug.ini || true


install:
    - composer install --no-interaction

script:
    - ./vendor/bin/tester $NTESTER_FLAGS -s -c ./tests/php-travis.ini -i
    - ./vendor/bin/tester $NTESTER_FLAGS -s -c ./tests/php-travis.ini ./tests

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      && php php-coveralls.phar --verbose --config tests/.coveralls.yml
      || true;
      fi

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done
